ServerName localhost

LoadModule rewrite_module modules/mod_rewrite.so

ErrorLog /dev/stderr

<VirtualHost *:80>
    DocumentRoot ${APACHE_DOCUMENT_ROOT}

    <Directory ${APACHE_DOCUMENT_ROOT}>
        Options -Indexes
        AllowOverride All
        Require all granted
    </Directory>

    DirectoryIndex index.php

    ProxyPassMatch "^/(.*\.php(/.*)?)$" "fcgi://127.0.0.1:9000${APACHE_DOCUMENT_ROOT}/$1"

    ErrorLog /dev/stderr
    CustomLog /dev/stdout combined
</VirtualHost>